// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.2
// source: api/v1/wal.proto

package wal_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Key       []byte `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Pattern   []byte `protobuf:"bytes,3,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	Action    uint32 `protobuf:"varint,4,opt,name=Action,proto3" json:"Action,omitempty"`
}

func (x *WalEntry) Reset() {
	*x = WalEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_wal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalEntry) ProtoMessage() {}

func (x *WalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalEntry.ProtoReflect.Descriptor instead.
func (*WalEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WalEntry) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WalEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WalEntry) GetPattern() []byte {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *WalEntry) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// Request the entry at or after the timestamp
type PublishEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *PublishEntryRequest) Reset() {
	*x = PublishEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_wal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEntryRequest) ProtoMessage() {}

func (x *PublishEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEntryRequest.ProtoReflect.Descriptor instead.
func (*PublishEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_wal_proto_rawDescGZIP(), []int{1}
}

func (x *PublishEntryRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PublishEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string    `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	Entry    *WalEntry `protobuf:"bytes,2,opt,name=Entry,proto3" json:"Entry,omitempty"`
}

func (x *PublishEntryResponse) Reset() {
	*x = PublishEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_wal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEntryResponse) ProtoMessage() {}

func (x *PublishEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEntryResponse.ProtoReflect.Descriptor instead.
func (*PublishEntryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_wal_proto_rawDescGZIP(), []int{2}
}

func (x *PublishEntryResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PublishEntryResponse) GetEntry() *WalEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type LogEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string    `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	Entry    *WalEntry `protobuf:"bytes,2,opt,name=Entry,proto3" json:"Entry,omitempty"`
}

func (x *LogEntryRequest) Reset() {
	*x = LogEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_wal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryRequest) ProtoMessage() {}

func (x *LogEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryRequest.ProtoReflect.Descriptor instead.
func (*LogEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_wal_proto_rawDescGZIP(), []int{3}
}

func (x *LogEntryRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LogEntryRequest) GetEntry() *WalEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type LogEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *LogEntryResponse) Reset() {
	*x = LogEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_wal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryResponse) ProtoMessage() {}

func (x *LogEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryResponse.ProtoReflect.Descriptor instead.
func (*LogEntryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_wal_proto_rawDescGZIP(), []int{4}
}

func (x *LogEntryResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_v1_wal_proto protoreflect.FileDescriptor

var file_api_v1_wal_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22,
	0x6c, 0x0a, 0x08, 0x57, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a,
	0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x5f, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x22, 0x5a, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22,
	0x30, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x32, 0x84, 0x02, 0x0a, 0x03, 0x57, 0x61, 0x6c, 0x12, 0x5d, 0x0a, 0x12, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x20, 0x2e, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x49, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x2e, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1c, 0x2e, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6d, 0x65, 0x72, 0x74, 0x65, 0x6e, 0x73, 0x2f,
	0x6d, 0x75, 0x6e, 0x63, 0x68, 0x6b, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x61, 0x6c,
	0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_wal_proto_rawDescOnce sync.Once
	file_api_v1_wal_proto_rawDescData = file_api_v1_wal_proto_rawDesc
)

func file_api_v1_wal_proto_rawDescGZIP() []byte {
	file_api_v1_wal_proto_rawDescOnce.Do(func() {
		file_api_v1_wal_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_wal_proto_rawDescData)
	})
	return file_api_v1_wal_proto_rawDescData
}

var file_api_v1_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_wal_proto_goTypes = []interface{}{
	(*WalEntry)(nil),             // 0: munchkin.v1.WalEntry
	(*PublishEntryRequest)(nil),  // 1: munchkin.v1.PublishEntryRequest
	(*PublishEntryResponse)(nil), // 2: munchkin.v1.PublishEntryResponse
	(*LogEntryRequest)(nil),      // 3: munchkin.v1.LogEntryRequest
	(*LogEntryResponse)(nil),     // 4: munchkin.v1.LogEntryResponse
}
var file_api_v1_wal_proto_depIdxs = []int32{
	0, // 0: munchkin.v1.PublishEntryResponse.Entry:type_name -> munchkin.v1.WalEntry
	0, // 1: munchkin.v1.LogEntryRequest.Entry:type_name -> munchkin.v1.WalEntry
	1, // 2: munchkin.v1.Wal.PublishEntryStream:input_type -> munchkin.v1.PublishEntryRequest
	3, // 3: munchkin.v1.Wal.LogEntry:input_type -> munchkin.v1.LogEntryRequest
	3, // 4: munchkin.v1.Wal.LogEntryStream:input_type -> munchkin.v1.LogEntryRequest
	2, // 5: munchkin.v1.Wal.PublishEntryStream:output_type -> munchkin.v1.PublishEntryResponse
	4, // 6: munchkin.v1.Wal.LogEntry:output_type -> munchkin.v1.LogEntryResponse
	4, // 7: munchkin.v1.Wal.LogEntryStream:output_type -> munchkin.v1.LogEntryResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_wal_proto_init() }
func file_api_v1_wal_proto_init() {
	if File_api_v1_wal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_wal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_wal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_wal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_wal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_wal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_wal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_wal_proto_goTypes,
		DependencyIndexes: file_api_v1_wal_proto_depIdxs,
		MessageInfos:      file_api_v1_wal_proto_msgTypes,
	}.Build()
	File_api_v1_wal_proto = out.File
	file_api_v1_wal_proto_rawDesc = nil
	file_api_v1_wal_proto_goTypes = nil
	file_api_v1_wal_proto_depIdxs = nil
}
